/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.gallery.common.metrics

import android.util.Log
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch

/**
 * Defines lifecycle operations for periodic system and hardware sensor telemetry.
 *
 * @param T The protobuf metrics container generated by this monitor.
 */
interface PeriodicSensorMonitor<T> {
  /**
   * Initializes monitor state, captures a baseline measurement, and starts background sampling on
   * [scope].
   */
  fun start(scope: CoroutineScope)

  /** Captures a single sensor reading and updates accumulated statistics. */
  fun sample()

  /** Constructs the current snapshot of aggregated metrics without halting sampling. */
  fun buildMetrics(): T

  /** Halts periodic sampling, captures a final measurement, and returns the finalized metrics. */
  fun stop(): T

  /** Cancels active sampling tasks and clears accumulated sensor history. */
  fun reset()
}

/**
 * Reusable coroutine-driven timer loop for periodic telemetry sampling.
 *
 * @param samplingInterval Configured interval between successive measurements.
 * @param dispatcher Coroutine dispatcher to run sampling loops on.
 * @param onSample Callback invoked periodically and at baseline startup.
 * @throws IllegalArgumentException if [samplingInterval] is not strictly positive.
 */
class PeriodicSampler(
  samplingInterval: Duration = DEFAULT_SAMPLING_INTERVAL,
  private val dispatcher: CoroutineDispatcher,
  private val onSample: () -> Unit,
) {
  val samplingInterval: Duration = samplingInterval.coerceAtLeast(MIN_SAMPLING_INTERVAL)

  init {
    require(samplingInterval > Duration.ZERO) {
      "Sampling interval must be strictly positive, but was $samplingInterval."
    }
    if (samplingInterval < MIN_SAMPLING_INTERVAL) {
      Log.d(
        TAG,
        "Sampling interval ($samplingInterval) is below the minimum threshold ($MIN_SAMPLING_INTERVAL). " +
          "Clamping to $MIN_SAMPLING_INTERVAL to avoid probe overhead.",
      )
    }
  }

  @Volatile private var samplingJob: Job? = null

  @Synchronized
  fun start(scope: CoroutineScope) {
    stop()
    onSample()
    samplingJob =
      scope.launch(dispatcher) {
        while (isActive) {
          delay(samplingInterval)
          onSample()
        }
      }
  }

  @Synchronized
  fun stop() {
    samplingJob?.cancel()
    samplingJob = null
  }

  companion object {
    private const val TAG = "AGPeriodicSampler"
    val MIN_SAMPLING_INTERVAL: Duration = 100.milliseconds
    val DEFAULT_SAMPLING_INTERVAL: Duration = 500.milliseconds
  }
}
